=== sgangavaram/WT-W-1/Note.dtd
<!ELEMENT Books (book*)>
<!ELEMENT book (Title, Author, ISBN_Number, Publisher, Edition, Price)>
<!ATTLIST book category CDATA #REQUIRED>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT ISBN_Number (#PCDATA)>
<!ELEMENT Publisher (#PCDATA)>
<!ELEMENT Edition (#PCDATA)>
<!ELEMENT Price (#PCDATA)>

=== sgangavaram/WT-W-1/Week-5/Book.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Book.xsl"?>
<!DOCTYPE Books SYSTEM "Note.dtd">
<Books>
    <book category="Fiction">
        <Title lang="en"> Jane Eyre </Title>
        <Author> Charlotte Bronte </Author>
        <ISBN_Number> 9780194241762 </ISBN_Number>
        <Publisher>  Smith, Elder and Co. of London. </Publisher>
        <Edition> 2011 Edition </Edition>
        <Price> $23.34 </Price>
    </book>
    <book category="Non-Fiction">
        <Title lang="en"> One in a millenial </Title>
        <Author> Kate Kennedy </Author>
        <ISBN_Number> 9781250285126 </ISBN_Number>
        <Publisher> St. Martin's Press </Publisher>
        <Edition> 2024 Edition </Edition>
        <Price> $14.57 </Price>
    </book>
    <book category="Fantasy">
        <Title lang="en"> The City of Stardust </Title>
        <Author> Georgia Summers </Author>
        <ISBN_Number> 9780316561488 </ISBN_Number>
        <Publisher> Redhook </Publisher>
        <Edition> 2024 Edition </Edition>
        <Price> $14.99 </Price>
    </book>
    <book category="Fiction">
        <Title lang="en"> Recipe for a Charmed Life </Title>
        <Author> Rachel Linden </Author>
        <ISBN_Number> 9780593440216 </ISBN_Number>
        <Publisher> Berkley </Publisher>
        <Edition> 2023 Edition </Edition>
        <Price> $11.99 </Price>
    </book>
    <book category="Non-Fiction">
        <Title lang="en"> Fluke: Chance, Chaos, and Why Everything We Do Matters </Title>
        <Author> Brian Klaas </Author>
        <ISBN_Number> 7780533440345  </ISBN_Number>
        <Publisher> Scribner  </Publisher>
        <Edition> 2021 Edition </Edition>
        <Price> $10.45 </Price>
    </book>
</Books>
